/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar un nuevo usuario */
        post: operations["registrarUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obtener token de acceso */
        post: operations["loginParaToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener todas las entradas (Notas y Tareas)
         * @description Retorna una lista de las entradas del usuario autenticado con soporte para filtrado y ordenamiento.
         */
        get: operations["listarEntries"];
        put?: never;
        /** Crear una nueva entrada */
        post: operations["crearEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener una entrada específica */
        get: operations["obtenerEntryPorId"];
        put?: never;
        post?: never;
        /** Eliminar una entrada específica */
        delete: operations["eliminarEntry"];
        options?: never;
        head?: never;
        /** Actualizar una entrada específica (metadata o contenido) */
        patch: operations["actualizarEntry"];
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir un recurso multimedia (imagen/dibujo) */
        post: operations["subirAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar un recurso multimedia */
        get: operations["obtenerAsset"];
        put?: never;
        post?: never;
        /** Eliminar un recurso multimedia */
        delete: operations["eliminarAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todas las columnas del tablero Kanban */
        get: operations["listarColumnas"];
        put?: never;
        /** Crear una nueva columna Kanban */
        post: operations["crearColumna"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/columns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar una columna Kanban */
        delete: operations["eliminarColumna"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todas las carpetas */
        get: operations["listarCarpetas"];
        put?: never;
        /** Crear una nueva carpeta */
        post: operations["crearCarpeta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar una carpeta */
        delete: operations["eliminarCarpeta"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Entry: {
            /** Format: int64 */
            readonly id?: number;
            /** @example Reunión de Prácticas */
            titulo: string;
            /**
             * @description Rich text content or encrypted blob
             * @example Discutir el avance del proyecto SDD.
             */
            contenido?: string;
            /** @enum {string} */
            type: "note" | "task";
            /** @default false */
            is_encrypted: boolean;
            /** @description JSON string containing client-side encryption metadata (IV, salt, algorithm hints) */
            encryption_metadata?: string;
            /** Format: date-time */
            readonly fecha_creacion?: string;
            /** Format: date-time */
            readonly fecha_modificacion?: string;
            /** @default 1 */
            readonly version: number;
            tags?: string[];
            folder_id?: number;
            /** @enum {string} */
            priority?: "low" | "medium" | "high";
            status_column?: string;
            /** Format: date-time */
            due_date?: string;
        };
        EntryUpdate: {
            titulo?: string;
            contenido?: string;
            is_encrypted?: boolean;
            encryption_metadata?: string;
            tags?: string[];
            folder_id?: number;
            /** @enum {string} */
            priority?: "low" | "medium" | "high";
            status_column?: string;
            /** Format: date-time */
            due_date?: string;
        };
        KanbanColumn: {
            id?: number;
            name?: string;
            position?: number;
        };
        KanbanColumnCreate: {
            name: string;
            position?: number;
        };
        Asset: {
            /** Format: uuid */
            id?: string;
            filename?: string;
            content_type?: string;
            size?: number;
            /** @description ID de la entrada a la que pertenece este recurso */
            entry_id?: number;
        };
        Folder: {
            id?: number;
            name?: string;
            parent_id?: number;
            /** @default false */
            is_encrypted: boolean;
            encryption_metadata?: string;
        };
        FolderCreate: {
            name: string;
            parent_id?: number;
            /** @default false */
            is_encrypted: boolean;
            encryption_metadata?: string;
        };
        UserCreate: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        Token: {
            access_token?: string;
            token_type?: string;
        };
        Error: {
            /** @example NOT_FOUND */
            codigo: string;
            /** @example El recurso solicitado no pudo ser localizado. */
            mensaje: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registrarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Usuario registrado con éxito. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El usuario ya existe o datos inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    loginParaToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Token obtenido con éxito. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Credenciales incorrectas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarEntries: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                type?: "note" | "task";
                status_column?: string;
                priority?: "low" | "medium" | "high";
                is_encrypted?: boolean;
                folder_id?: number;
                sort_by?: "fecha_creacion" | "due_date" | "priority" | "titulo";
                order?: "asc" | "desc";
                /** @description Keyword search in title and content */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Una lista de entradas obtenida con éxito. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
            /** @description No autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crearEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Entry"];
            };
        };
        responses: {
            /** @description Entrada creada con éxito. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datos de entrada inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtenerEntryPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description No encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eliminarEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    actualizarEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EntryUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description No encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subirAsset: {
        parameters: {
            query?: {
                entry_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    obtenerAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recurso obtenido. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eliminarAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarColumnas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KanbanColumn"][];
                };
            };
        };
    };
    crearColumna: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KanbanColumnCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KanbanColumn"];
                };
            };
        };
    };
    eliminarColumna: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listarCarpetas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Folder"][];
                };
            };
        };
    };
    crearCarpeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Folder"];
                };
            };
        };
    };
    eliminarCarpeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
